FROM python:3.14-alpine

WORKDIR /app
COPY requirements.txt .
# RUN apk add --no-cache wget

RUN pip install --no-cache-dir -r requirements.txt

COPY app app

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
  CMD wget --spider -q http://localhost:8000 || exit 1

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
